<?php
/**
 * ChangeStatusCode
 *
 * PHP version 5
 *
 * @category Class
 * @package  ASMP\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ASMP
 *
 * Application Server Management Protocol server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@asmp.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ASMP\Client\Model;
use \ASMP\Client\ObjectSerializer;

/**
 * ChangeStatusCode Class Doc Comment
 *
 * @category Class
 * @description Change Status Code:  * &#x60;202&#x60; - Change is pending  * &#x60;200&#x60; - Change has been completed  * &#x60;422&#x60; - The requested changeset can not be fulfilled  * &#x60;500&#x60; - An error occured
 * @package  ASMP\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChangeStatusCode
{
    /**
     * Possible values of this enum
     */
    const 202 = 202;
const 200 = 200;
const 422 = 422;
const 500 = 500;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::202,
self::200,
self::422,
self::500,        ];
    }
}
