<?php
/**
 * CheckResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ASMP\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ASMP
 *
 * Application Server Management Protocol server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@asmprotocol.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ASMP\Client;

/**
 * CheckResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CheckResponse
 * @package     ASMP\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CheckResponse"
     */
    public function testCheckResponse()
    {
    }

    /**
     * Test attribute "fullfilable"
     */
    public function testPropertyFullfilable()
    {
    }

    /**
     * Test attribute "components"
     */
    public function testPropertyComponents()
    {
    }
}
