<?php
/**
 * ConstraintTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ASMP
 *
 * Application Server Management Protocol server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@asmprotocol.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConstraintTest Class Doc Comment
 *
 * @category    Class
 * @description Defining a component contraint using an operator -&gt; value property. A constraint can only hold one property.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConstraintTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Constraint"
     */
    public function testConstraint()
    {
    }

    /**
     * Test attribute ""
     */
    public function testProperty()
    {
    }

    /**
     * Test attribute ""
     */
    public function testProperty()
    {
    }

    /**
     * Test attribute ""
     */
    public function testProperty()
    {
    }

    /**
     * Test attribute ""
     */
    public function testProperty()
    {
    }

    /**
     * Test attribute ""
     */
    public function testProperty()
    {
    }

    /**
     * Test attribute ""
     */
    public function testProperty()
    {
    }
}
