<?php
/**
 * ChangeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ASMP\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ASMP
 *
 * Application Server Management Protocol server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@asmprotocol.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ASMP\Client;

use ASMP\Client\Configuration;
use ASMP\Client\ApiException;
use ASMP\Client\ObjectSerializer;

/**
 * ChangeApiTest Class Doc Comment
 *
 * @category Class
 * @package  ASMP\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChangeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for change
     *
     * Request a specific change for one or multiple components as previously checked in a /check request.
     *
     */
    public function testChange()
    {
    }
}
